import testData from '../test-data.json';
import { test, expect } from '../utils/smart-test.js';
 
test('generated flow @sanity', async ({ page }) => {
    await page.goto(testData.url);
    await page.waitForLoadState('domcontentloaded');
    await page.locator("xpath=//input[@*[name()='type' and .='text']]").click();
    await page.getByRole('textbox', { name: 'Enter your username or email' }).fill(testData.signInName);
    await page.locator("xpath=//button[@*[name()='type' and .='submit']]").click();
    await page.locator("xpath=//input[@*[name()='type' and .='password']]").click();
    await page.getByRole('textbox', { name: 'Password' }).fill(testData.pass);
    await page.locator("xpath=//button[@*[name()='type' and .='submit']]").click();
    await page.getByRole('searchbox', { name: 'Search' }).fill(testData.search);
    await page.locator("xpath=//span[@*[name()='data-pc-section' and .='nodelabel']]").click();
    await page.locator("xpath=//a[@*[name()='href' and .='/corsair/shipment/list']]").click();
    await page.locator("xpath=//a[@*[name()='data-pc-name' and .='button']]").click();
    await page.locator("xpath=//span[@*[name()='aria-label' and .='Find an order template']]/following-sibling::div[@*[name()='data-pc-section' and .='dropdown']]").click();
    await page.locator("xpath=//li[@*[name()='aria-label' and .='demo']]").click();
    await page.locator("xpath=//button[@*[name()='data-p' and .='rounded']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Add Quote']]").click();
    await page.locator("xpath=//span[@*[name()='aria-label' and .='Mode']]/following-sibling::div[@*[name()='data-pc-section' and .='dropdown']]").click();
    await page.locator("xpath=//li[@*[name()='aria-label' and .='TL']]").click();
    await page.locator("xpath=//tfoot[@*[name()='data-p-scrollable' and .='true']]/preceding::tr[normalize-space(.)='LinehaulBuy RateMarginFlatSell Rate']//input[@*[name()='aria-valuemin' and .='0']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Save Quote']]").click();
    await page.locator("xpath=//button[@*[name()='aria-hidden' and .='false']]").click();
    await page.locator("xpath=//span[@*[name()='data-pc-section' and .='lastfocusableelement']]/preceding::button[normalize-space(.)='Confirm']").click();
    await page.locator("xpath=//button[@*[name()='data-p' and .='icon-only outlined']]/preceding-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Add Pickup']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-arrival']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//td[@*[name()='aria-label' and .='12']]//span[@*[name()='data-pc-section' and .='day']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-arrival']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-departure']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//td[@*[name()='aria-label' and .='20']]//span[@*[name()='data-pc-section' and .='day']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Save Event']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Add Delivery']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-arrival']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//td[@*[name()='aria-label' and .='25']]/following::td[@*[name()='aria-label' and .='26']]//span[@*[name()='data-pc-section' and .='day']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-arrival']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//input[@*[name()='id' and .='actual-departure']]/following-sibling::button[@*[name()='type' and .='button']]").click();
    await page.locator("xpath=//td[@*[name()='aria-label' and .='25']]/following::td[@*[name()='aria-label' and .='28']]//span[@*[name()='data-pc-section' and .='day']]").click();
    await page.locator("xpath=//button[@*[name()='aria-label' and .='Save Event']]").click();
});